/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Suchitra
 */
import java.awt.*;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Main extends javax.swing.JFrame {
Connection con = null;
Statement st = null;
ResultSet rs = null;
int accno1;
int accno2;
String sql;
String payer = "";
String payee = "";
int in = 0;
//for encryption
String euname="",epwd="";
int n=9;
String adp="";

ImageIcon icon1 = new ImageIcon(getClass().getResource("Images/cancel.png"));        
ImageIcon icon2 = new ImageIcon(getClass().getResource("Images/ok.png"));
    /**
     * Creates new form Main
     */
//encryption method
String encry(String pa,String adp,int  n){
int arr[]=new int[20];
        int ar2[]=new int[20];double p[]=new double[20];
  int ar3[]=new int[20];      int ps[]=new int[20]; 
 try{
     for(int i=0;i<20;i++)
  {arr[i]=0;ar2[i]=0;ar3[i]=0;p[i]=0;
  }
for(int i=0;i<pa.length();i++)
{if(i<pa.length())
 arr[i]=(int)pa.charAt(i);else arr[i]=0;
if(i<adp.length())
    ar2[i]=(int)adp.charAt(i);
else
    ar2[i]=0;
}
    
    for (int i=0;i<pa.length();i++)
    {
            ar3[i]=arr[i]+ar2[i];

        String pp1="";
    int j=0,maxt=0;double sp=ar3[i];
    
 for(int t=1;sp>=Math.pow(n,t);t++)
 maxt=t;
        System.out.println("maxt"+maxt);             
do
{p[j]=(sp-(sp%Math.pow(n,maxt-j)))/Math.pow(n,maxt-j);
sp=sp%Math.pow(n,maxt-j);
pp1=pp1+(int)p[j];j++;
}while(j<=maxt);
 ps[i]=Integer.parseInt(pp1);
 System.out.println(ps[i]+"   ,"+"/n"+ar3[i]);
    } }catch(Exception e)
            {System.out.println(e.getMessage());}
 String p3="";
  for (int l=0;l<pa.length();l++)
      p3+=ps[l]+",";
  return(p3);
}
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginMain = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TF1 = new javax.swing.JTextField();
        PF1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        SignUpConf = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SignUp = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TF4 = new javax.swing.JTextField();
        PF2 = new javax.swing.JPasswordField();
        PF3 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        LoggedIn = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        I1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        I2 = new javax.swing.JLabel();
        I3 = new javax.swing.JLabel();
        I = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        I4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ContactUsF = new javax.swing.JFrame();
        scroll = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        AboutUsF = new javax.swing.JFrame();
        scroll2 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        Transfer = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Update = new javax.swing.JFrame();
        jTextField4 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        TransferHist = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        AccDet = new javax.swing.JFrame();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Report = new javax.swing.JFrame();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        LoginMain.setMinimumSize(new java.awt.Dimension(640, 480));
        LoginMain.setResizable(false);
        LoginMain.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Login to your account");
        LoginMain.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 170, 30));

        jLabel2.setText("Don't have an account, Create one");
        LoginMain.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 190, 30));

        jLabel3.setText("Username");
        LoginMain.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 100, 30));

        jLabel4.setText("Password");
        LoginMain.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 100, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/Signup.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        LoginMain.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 100, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/login.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        LoginMain.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 100, 30));
        LoginMain.getContentPane().add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 100, 30));
        LoginMain.getContentPane().add(PF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 100, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.jpg"))); // NOI18N
        LoginMain.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        SignUpConf.setBackground(new java.awt.Color(68, 136, 181));
        SignUpConf.setMinimumSize(new java.awt.Dimension(640, 480));
        SignUpConf.setResizable(false);
        SignUpConf.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                SignUpConfWindowActivated(evt);
            }
        });
        SignUpConf.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Enter Account No.");
        SignUpConf.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 100, 30));

        jLabel6.setText("Account Name");
        SignUpConf.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 100, 30));
        SignUpConf.getContentPane().add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 30));
        SignUpConf.getContentPane().add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 100, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/submitblue.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        SignUpConf.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 100, 30));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/readthereportblue.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        SignUpConf.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 155, 35));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/readthereportblue.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        SignUpConf.getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 155, 35));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A2.jpg"))); // NOI18N
        SignUpConf.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 262, 240));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Q2.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel33MouseExited(evt);
            }
        });
        SignUpConf.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 262, 240));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A1.jpg"))); // NOI18N
        SignUpConf.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 262, 240));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Q1.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });
        SignUpConf.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 262, 240));

        jLabel8.setBackground(new java.awt.Color(68, 136, 181));
        jLabel8.setOpaque(true);
        SignUpConf.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 378, 480));

        SignUp.setMinimumSize(new java.awt.Dimension(640, 480));
        SignUp.setResizable(false);
        SignUp.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Enter Username");
        SignUp.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, 30));

        jLabel11.setText("Enter Password");
        SignUp.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, 30));

        jLabel12.setText("Confirm Password");
        SignUp.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, 30));
        SignUp.getContentPane().add(TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 100, 30));
        SignUp.getContentPane().add(PF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 100, 30));
        SignUp.getContentPane().add(PF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/submit.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        SignUp.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 100, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.jpg"))); // NOI18N
        SignUp.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        LoggedIn.setMinimumSize(new java.awt.Dimension(640, 480));
        LoggedIn.setResizable(false);
        LoggedIn.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("DashBoard");
        LoggedIn.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 37, 150, 30));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/moneytrans.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        LoggedIn.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 200, 30));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/logout.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        LoggedIn.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 100, 30));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/accdetails.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        LoggedIn.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 200, 30));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/delacc.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        LoggedIn.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 200, 30));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/accacti.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        LoggedIn.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 200, 30));
        LoggedIn.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 140, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("...");
        LoggedIn.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));
        LoggedIn.getContentPane().add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, 30));

        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Account Options"));
        LoggedIn.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 220, 330));
        LoggedIn.getContentPane().add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, 30));
        LoggedIn.getContentPane().add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, 30));
        LoggedIn.getContentPane().add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 30));

        jLabel13.setText("Email ID Verified");
        LoggedIn.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 30));

        jLabel25.setText("Contact No. Added");
        LoggedIn.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, 30));

        jLabel26.setText("Address Added");
        LoggedIn.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 150, 30));
        LoggedIn.getContentPane().add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, 30));

        jLabel31.setText("Backup E-Mail Added");
        LoggedIn.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 150, 30));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7.jpg"))); // NOI18N
        LoggedIn.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        ContactUsF.setMinimumSize(new java.awt.Dimension(640, 480));
        ContactUsF.setResizable(false);
        ContactUsF.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                ContactUsFWindowActivated(evt);
            }
        });
        ContactUsF.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area.setEditable(false);
        area.setColumns(20);
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setRows(5);
        area.setText("Procash Bank N.A., India Branch Contacts\n\nProcash Bank N.A., Mumbai Branch\nAddress: Procash Tower, Off CST Road, Kalina, Santacruz East, Mumbai, \n400098, India\nPhone: +91 22 6157 3000\n\nProcash Bank N.A., New Delhi Branch\nAddress: Unit nos. 401 and 402, 4th floor, ‘New Tower’, Block A, \nHyatt Regency Delhi, BhikajiCama Place, New Delhi – 110 066\nPhone: +91 11 66111700\n\nManaging Director & Bank CEO\nMr. Ashwin Iyer\nAddress: Procash Tower, Off CST Road, Kalina, Santacruz East, Mumbai, \n400098, India\nPhone: +917741092502\n\nSenior Country Business Manager\nMr. Pranav Birari\nAddress: Procash Tower, Off CST Road, Kalina, Santacruz East, Mumbai, \n400098, India\nPhone: +918983703920\n\nPrincipal Nodal Officer\nMr. Lekhit Borole\nAddress: Procash Tower, Off CST Road, Kalina, Santacruz East, Mumbai, \n400098, India\nPhone: +91 22 6157 3698\nEmail: borolelekhit.pno@procash.com\n\nHelpdesk Queries: Client Services, Procash Tower, Off CST Road, Kalina, \nSantacruz East, Mumbai, 400098, India\nPhone: +91 22 61573000\nFax: +91-22-66466204 / 66466542 / 39142704 / 39142705\n\nGrievance Handling Mechanism\nFor any grievance or issues, customers can email their complaint to: \ncustomerservice.india@procash.com.\n\nCustomers will receive a response within 10 business days and we shall do \nour best to resolve the complaint to the customer’s satisfaction within \nthis period. Complex complaints which would require time for examination \nof issues involved, may take a longer time to resolve. However, in such \ncases, customers will be informed about the status of their complaint \nwithin this period. Our focus would remain on the quality and completeness \nof the response, with speed of delivery being an important but not \noverriding factor.\n\nIn case of unsatisfactory response from the above channel, customers can \nescalate the complaint to the Principal Nodal Officer of the Bank:\nCustomers will receive a response within 10 business days and they will \nhave to quote thereference number pertaining to their earlier contact with\nthe Bank on the same issue.\n\nGrievance handling procedure and information on Banking Ombudsman\nIf you do not receive any response from us within one month from the date \nof receipt of your complaint, or if you are not satisfied with the reply \ngiven by us, you may approach the Banking Ombudsman at the following \naddress:\n\nThe details of the Banking Ombudsman Scheme, as well as the contact details \nof the Ombudsman for respective City or State, are available on \nwww.bankingombudsman.rbi.org.in. This link is displayed on our website as \nwell. A copy of this Scheme is available on request.\nFor the convenience of the customers, the following are displayed on our \nwebsite:\n    \n    Appropriate arrangement for receiving complaints and suggestions\n    The name, address and contact number of the Principal Nodal Officer\n    Contact details of Banking Ombudsman of the area\n    Code of bank’s commitments to customers/Fair Practice code\n\nThe nodal officer of the Bank is kept informed on the complaints which are \nnot redressed within one month. The details of the Banking Ombudsman which\nthe complainant can approach are included in the final closure letters\n/emails for such cases.\n");
        area.setMinimumSize(new java.awt.Dimension(610, 1300));
        area.setPreferredSize(new java.awt.Dimension(610, 1300));
        scroll.setViewportView(area);

        ContactUsF.getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 633, 480));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.jpg"))); // NOI18N
        ContactUsF.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        AboutUsF.setMinimumSize(new java.awt.Dimension(640, 480));
        AboutUsF.setResizable(false);
        AboutUsF.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                AboutUsFWindowActivated(evt);
            }
        });
        AboutUsF.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area2.setEditable(false);
        area2.setColumns(20);
        area2.setRows(5);
        area2.setText("\nOur presence in India began in 1922, when a heritage firm took an ownership \ninterest in a merchant bank in Calcutta. Today, we provide clients in India a\ncomprehensive range of corporate and investment banking services. Our global \nService centres in Mumbai, Bangalore and Hyderabad support operations globally.\n\nWe have operated in Asia Pacific since 1872, and today are present across 17\ncountries in the region. Local corporations and institutions, multinationals,\ngovernments and private clients rely on us for market-leading financial \nservices — a confidence bred from our strength and ability to deliver \nintegrated services across the Corporate & Investment Bank, Asset Management\nand the Private Bank.\n\nIn Asia Pacific, we are committed to helping promote economic growth and\neconomic inclusion through our key philanthropic initiatives in the areas of\nworkforce readiness, small business development and financial capability. \nOur investments aim to increase the number of quality jobs created for the \nunderserved individuals and communities, helping small businesses become more\nsustainable, as well as assisting marginalized people in gaining access to \naffordable financial products so that they can become more financially secure.\nThis shared commitment to the community drives our Foundation’s giving and\nemployee engagement and volunteering activities across the region.\n\nProcash is a global leader in financial services, offering solutions to the \nWorld's most important corporations, governments and institutions in more \nthan 100 countries. The Firm and its Foundation give approximately US$200 \nmillion annually to non-profit organizations around the world. We also lead \nvolunteer service activities for employees in local communities by utilizing\nour many resources, including those that stem from access to capital, \neconomies of scale, global reach and expertise.\n");
        area2.setMinimumSize(new java.awt.Dimension(610, 570));
        area2.setPreferredSize(new java.awt.Dimension(610, 570));
        scroll2.setViewportView(area2);

        AboutUsF.getContentPane().add(scroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 633, 480));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6.jpg"))); // NOI18N
        AboutUsF.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        Transfer.setMinimumSize(new java.awt.Dimension(640, 480));
        Transfer.setResizable(false);
        Transfer.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                TransferWindowActivated(evt);
            }
        });
        Transfer.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Enter Payee Acc. No.");
        Transfer.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 150, 30));

        jLabel19.setText("Enter Amount");
        Transfer.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 150, 30));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/transfer.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Transfer.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 100, 30));
        Transfer.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 149, 100, 30));
        Transfer.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 207, 100, 30));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/readthereportorange.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        Transfer.getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 160, 35));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/readthereportorange.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        Transfer.getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 160, 35));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A3.jpg"))); // NOI18N
        Transfer.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 262, 240));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Q3.png"))); // NOI18N
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel40MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel40MouseExited(evt);
            }
        });
        Transfer.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 262, 240));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A4.jpg"))); // NOI18N
        Transfer.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 262, 240));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Q4.png"))); // NOI18N
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel39MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel39MouseExited(evt);
            }
        });
        Transfer.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 262, 240));

        jLabel41.setBackground(new java.awt.Color(237, 135, 61));
        jLabel41.setOpaque(true);
        Transfer.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 380, 480));

        Update.setMinimumSize(new java.awt.Dimension(640, 480));
        Update.setResizable(false);
        Update.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Update.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 208, 350, 30));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/update.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Update.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 100, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Update.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 89, 350, -1));

        jCheckBox1.setText("Update Address");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Update.getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 89, 150, 30));

        jCheckBox2.setText("Update Contact No.");
        jCheckBox2.setOpaque(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        Update.getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 208, 150, 30));

        jCheckBox3.setText("Update Backup E-Mail ID");
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        Update.getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 256, 150, 30));
        Update.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 256, 350, 30));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/cancelbut.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        Update.getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 366, 100, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/8.jpg"))); // NOI18N
        Update.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        TransferHist.setMinimumSize(new java.awt.Dimension(640, 480));
        TransferHist.setResizable(false);
        TransferHist.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payer", "Payee", "Amount", "Date", "Time"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        TransferHist.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 620, 400));

        jLabel38.setBackground(new java.awt.Color(0, 102, 102));
        jLabel38.setOpaque(true);
        TransferHist.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        AccDet.setMinimumSize(new java.awt.Dimension(640, 480));
        AccDet.setResizable(false);
        AccDet.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/Updateinfo.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        AccDet.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 289, 100, 30));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/refresh.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        AccDet.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 289, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Name", "Address"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        AccDet.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 600, 60));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contact No.", "Backup Email"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        AccDet.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 600, 60));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Account No.");
        AccDet.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 70, 30));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Balance -");
        AccDet.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 43, 50, 30));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        AccDet.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 43, 100, 30));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        AccDet.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 43, 100, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5.jpg"))); // NOI18N
        AccDet.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        Report.setMinimumSize(new java.awt.Dimension(640, 480));
        Report.setResizable(false);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/error.png"))); // NOI18N

        javax.swing.GroupLayout ReportLayout = new javax.swing.GroupLayout(Report.getContentPane());
        Report.getContentPane().setLayout(ReportLayout);
        ReportLayout.setHorizontalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ReportLayout.setVerticalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/login.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 100, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/contactus.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 100, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/aboutus.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 30));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buttons/exit.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 100, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
LoginMain.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
SignUpConf.setVisible(true);
LoginMain.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String uname = TF1.getText();
String pwd = new String(PF1.getPassword());

Main ob=new Main(); //decrypt
pwd=ob.encry(pwd, adp, n);

try{
        TF1.setText("");
        PF1.setText("");
        TF1.requestFocus();
sql = "select * from user where Username = '"+uname+"' and Password = '"+pwd+"';";
rs = st.executeQuery(sql);
rs.first();

if(rs.getString(4).equals(uname) && rs.getString(5).equals(pwd)){
        LoginMain.setVisible(false);
        LoggedIn.setVisible(true);
        accno2 = rs.getInt(1);
        payer = rs.getString(2);
        
        jLabel21.setText("Welcome "+uname);

  rs.getString(9);
    if(rs.wasNull()){
        I1.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I1.setIcon(icon2);
    }
  rs.getString(6);
    if(rs.wasNull()){
        I2.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I2.setIcon(icon2);
    }
  rs.getString(7);
    if(rs.wasNull()){
        I3.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I3.setIcon(icon2);
    }
   
  rs.getString(9);
    if(rs.wasNull()){
        I4.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I4.setIcon(icon2);
    }
    
}
}
catch(Exception e){
JOptionPane.showMessageDialog(rootPane, "Invalid Credentials, Contact admin if forgot Password. "+"\n"+e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int accno = Integer.parseInt(TF2.getText());
String accuser = TF3.getText();

try{
        TF3.setText("");
        TF2.setText("");
        TF2.requestFocus();
sql = "select * from user where AccNo = '"+accno+"' and AccName = '"+accuser+"';";
rs = st.executeQuery(sql);
rs.first();

String status = rs.getString(8);
accno1 = rs.getInt(1);
rs.getString(4);

    if(rs.wasNull() && status.equals("Active")){
        
       SignUp.setVisible(true);
       SignUpConf.setVisible(false);
    }
    else if(status.equals("Inactive")){
    JOptionPane.showMessageDialog(rootPane, "Your Account is inactive. This might be due to the following reasons:- "+"\n"+"1. Deletition of netBanking account"+"\n"+"2. Suspension of account due to violation of our Policy"+"\n"+"Contact Admin for further Details.");
    
    }
    else{
       JOptionPane.showMessageDialog(rootPane, "Account already exists, Redirecting to login Page");
       SignUpConf.setVisible(false);
       LoginMain.setVisible(true);
    }
}
catch(Exception e){
JOptionPane.showMessageDialog(rootPane, "Invalid Details, Contact admin if you don't have a savings account."+"\n"+e.getMessage());
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Main ob=new Main();
String username = TF4.getText();
String pwd1 = new String(PF2.getPassword());
String pwd2 = new String(PF3.getPassword());

if(pwd1.equals(pwd2)){
   pwd1=ob.encry(pwd1,adp,n);
try{
    TF4.setText("");
    PF2.setText("");
    PF3.setText("");
    TF4.requestFocus();

      sql = "update user set Username = '"+username+"' where AccNo = '"+accno1+"';";
      st.executeUpdate(sql);
      sql = "update user set Password = '"+pwd1+"' where AccNo = '"+accno1+"';";
      st.executeUpdate(sql);
  
        JOptionPane.showMessageDialog(rootPane, "Account succesfully created, You will be redirected to the login page");
        LoginMain.setVisible(true);
        SignUp.setVisible(false);
    
}
catch(Exception e){
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}
}
else{
    JOptionPane.showMessageDialog(rootPane, "Password not matching, Re-Enter password");
    PF2.setText("");
    PF3.setText("");
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
try{
Class.forName("java.sql.Driver");
con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","1234");
st = con.createStatement();
}

catch(Exception e){
JOptionPane.showMessageDialog(rootPane, e.getMessage());
}

LoginMain.setLocationRelativeTo(null);
SignUpConf.setLocationRelativeTo(null);
SignUp.setLocationRelativeTo(null);
LoggedIn.setLocationRelativeTo(null);
ContactUsF.setLocationRelativeTo(null);
AboutUsF.setLocationRelativeTo(null);
Transfer.setLocationRelativeTo(null);
Update.setLocationRelativeTo(null);
TransferHist.setLocationRelativeTo(null);
AccDet.setLocationRelativeTo(null);
Report.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
ContactUsF.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ContactUsFWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ContactUsFWindowActivated
scroll.setOpaque(false);  
scroll.getViewport().setOpaque(false);
scroll.setBorder(null);
scroll.setViewportBorder(null);
area.setBorder(null);
area.setBackground(new Color(0,0,0,64));
    }//GEN-LAST:event_ContactUsFWindowActivated

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
AboutUsF.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void AboutUsFWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AboutUsFWindowActivated
scroll2.setOpaque(false);  
scroll2.getViewport().setOpaque(false);
scroll2.setBorder(null);
scroll2.setViewportBorder(null);
area2.setBorder(null);
area2.setBackground(new Color(0,0,0,64));
    }//GEN-LAST:event_AboutUsFWindowActivated

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Transfer.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   int acct = Integer.parseInt(jTextField1.getText());
   int amt = Integer.parseInt(jTextField2.getText());
        jTextField1.setText("");
        jTextField2.setText("");
        Transfer.setVisible(false);
        
in = JOptionPane.showOptionDialog(rootPane, "Do you want to proceed with the Transaction", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
if(in == JOptionPane.OK_OPTION){
 try{
 
    sql = "select * from user where AccNo = '"+accno2+"';";
    rs = st.executeQuery(sql);
    rs.first();
    
    int bal1 = rs.getInt(3);
    int newbal = bal1 - amt;
    
    sql = "Update user set Balance = '"+newbal+"' where AccNo = '"+accno2+"';";
    st.executeUpdate(sql);
    
    sql = "select * from user where AccNo = '"+acct+"';";
    rs = st.executeQuery(sql);
    rs.first();
    
    payee = rs.getString(2);
    int bal2 = rs.getInt(3);
    int newbal2 = bal2 + amt;
    
    sql = "Update user set Balance = '"+newbal2+"' where AccNo = '"+acct+"';";
    st.executeUpdate(sql);
    
       JOptionPane.showMessageDialog(rootPane,"Transaction Successful");
    
    sql = "insert into trhis values('"+payer+"','"+payee+"','"+amt+"',curdate(),curtime());";
    st.executeUpdate(sql);
  }
 
 catch(Exception e){
    JOptionPane.showMessageDialog(rootPane,"Invalid Details. "+"\n"+e.getMessage());
    }
}

else if(in == JOptionPane.CANCEL_OPTION){
JOptionPane.showMessageDialog(rootPane, "Transaction Aborted");
}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
LoggedIn.setVisible(false);
LoginMain.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
in = JOptionPane.showOptionDialog(rootPane, "Are You sure you want to delete your Account?"+"\n"+"This cannot be undone.", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

if(in == JOptionPane.OK_OPTION){
try{

sql = "update user set Username = null where AccNo = '"+accno2+"';";
st.executeUpdate(sql);

sql = "update user set Password = null where AccNo = '"+accno2+"';";
st.executeUpdate(sql);

sql = "update user set Status = 'Inactive' where AccNo = '"+accno2+"';";
st.executeUpdate(sql);

JOptionPane.showMessageDialog(rootPane, "Account Deleted.");
LoggedIn.setVisible(false);

}
catch(Exception e){
    JOptionPane.showMessageDialog(rootPane,e.getMessage());
}
}

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
in = JOptionPane.showOptionDialog(rootPane, "Do you want to proceed with the Update?", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE,null,null,null);
if(in == JOptionPane.OK_OPTION){      
  try{   
  if(jCheckBox1.isSelected()){
     String a=jTextArea1.getText();
         if(a.equals("")){
           JOptionPane.showMessageDialog(rootPane, "Invalid Adress");
         }
         else{
           sql = "Update user set Address='"+a+"' where AccNo='"+accno2+"';";
           st.executeUpdate(sql);
         }
  }
 
  if(jCheckBox2.isSelected()){
     String m=jTextField4.getText();
         if(m.equals("") || m.length()!=10){
           JOptionPane.showMessageDialog(rootPane, "Invalid Contact No.");
         }
         else{  
           sql = "Update user set Phone='"+m+"' where AccNo='"+accno2+"';";
           st.executeUpdate(sql);
         }
  }

  if(jCheckBox3.isSelected()){
     String e=jTextField3.getText();
         if(e.equals("")){
           JOptionPane.showMessageDialog(rootPane, "Invalid Adress");
         }
         else{  
           sql = "Update user set BackUpEmail='"+e+"' where AccNo='"+accno2+"';";
           st.executeUpdate(sql);
         }
  }

     if(jCheckBox1.isSelected() == false && jCheckBox2.isSelected() == false && jCheckBox3.isSelected() == false){
      JOptionPane.showMessageDialog(rootPane,"No Records Updated");
     }
     else{
      JOptionPane.showMessageDialog(rootPane,"Records Updated Successfully");
     }
  
  jTextArea1.setText("");
  jTextField3.setText("");
  jTextField4.setText("");
  jTextArea1.setEditable(false);
  jTextField3.setEditable(false);
  jTextField4.setEditable(false);
  Update.setVisible(false);
  AccDet.setVisible(true);
  jCheckBox1.setSelected(false);
  jCheckBox2.setSelected(false);
  jCheckBox3.setSelected(false);
  
sql = "select * from user where AccNo = '"+accno2+"';";
rs = st.executeQuery(sql);
rs.first();
  rs.getString(9);
    if(rs.wasNull()){
        I1.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I1.setIcon(icon2);
    }
  rs.getString(6);
    if(rs.wasNull()){
        I2.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I2.setIcon(icon2);
    }
  rs.getString(7);
    if(rs.wasNull()){
        I3.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I3.setIcon(icon2);
    }
   
  rs.getString(9);
    if(rs.wasNull()){
        I4.setIcon(icon1);
        I.setText("Your account requires attention:-");
    }
    else{
        I4.setIcon(icon2);
    }
  
  }
  catch(Exception e){
  JOptionPane.showMessageDialog(rootPane, e.getMessage());
  }
}
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
TransferHist.setVisible(true); 

DefaultTableModel tm=(DefaultTableModel)jTable3.getModel();
tm.setRowCount(0);
try
{

sql="Select * from trhis where Payer = '"+payer+"';";
rs=st.executeQuery(sql);

while(rs.next()){
Object arr[]={rs.getString(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getString(5)};
tm.addRow(arr);
}

sql="Select * from trhis where Payee = '"+payer+"';";
rs=st.executeQuery(sql);

while(rs.next()){
Object arr[]={rs.getString(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getString(5)};
tm.addRow(arr);

}
}

catch(Exception e){
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
AccDet.setVisible(true);
try{
DefaultTableModel tm1 = (DefaultTableModel)jTable1.getModel();
DefaultTableModel tm2 = (DefaultTableModel)jTable2.getModel();
    tm1.setRowCount(0);
    tm2.setRowCount(0);

    sql = "select * from user where AccNo = '"+accno2+"';";
    rs = st.executeQuery(sql);
    rs.first();

Object arr1[] = {rs.getString(2),rs.getString(7)};
Object arr2[] = {rs.getString(6),rs.getString(9)};

tm1.addRow(arr1);
tm2.addRow(arr2);

jLabel29.setText(""+rs.getInt(1));
jLabel30.setText(""+rs.getInt(3));
}
catch(Exception e){
JOptionPane.showMessageDialog(rootPane, e.getMessage());
}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
AccDet.setVisible(false);
Update.setVisible(true);
jTextArea1.setEditable(false);
jTextField3.setEditable(false);
jTextField4.setEditable(false);
  jCheckBox1.setSelected(false);
  jCheckBox2.setSelected(false);
  jCheckBox3.setSelected(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
try{
DefaultTableModel tm1 = (DefaultTableModel)jTable1.getModel();
DefaultTableModel tm2 = (DefaultTableModel)jTable2.getModel();
tm1.removeRow(0);
tm2.removeRow(0);

    sql = "select * from user where AccNo = '"+accno2+"';";
    rs = st.executeQuery(sql);
    rs.first();

Object arr1[] = {rs.getString(2),rs.getString(7)};
Object arr2[] = {rs.getString(6),rs.getString(9)};

tm1.addRow(arr1);
tm2.addRow(arr2);

}
catch(Exception e){
JOptionPane.showMessageDialog(rootPane, e.getMessage());
}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
  jTextArea1.setText("");
  jTextField3.setText("");
  jTextField4.setText("");
  jTextArea1.setEditable(false);
  jTextField3.setEditable(false);
  jTextField4.setEditable(false);
  Update.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
if(jCheckBox1.isSelected()){
   jTextArea1.setEditable(true);
   }        
else{
   jTextArea1.setEditable(false);
   jTextArea1.setText("");
   }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
if(jCheckBox2.isSelected()){
   jTextField4.setEditable(true); 
   }        
else{
   jTextField4.setEditable(false); 
   jTextField4.setText("");
   }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
if(jCheckBox3.isSelected()){
   jTextField3.setEditable(true); 
   }        
else{
   jTextField3.setEditable(false); 
   jTextField3.setText("");
   }    
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
jLabel34.setVisible(true);
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
jLabel34.setVisible(false);
    }//GEN-LAST:event_jLabel32MouseExited

    private void jLabel33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseEntered
jLabel35.setVisible(true);
    }//GEN-LAST:event_jLabel33MouseEntered

    private void jLabel33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseExited
jLabel35.setVisible(false);
    }//GEN-LAST:event_jLabel33MouseExited

    private void SignUpConfWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SignUpConfWindowActivated
jLabel34.setVisible(false);
jLabel35.setVisible(false);
    }//GEN-LAST:event_SignUpConfWindowActivated

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
Report.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
Report.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jLabel40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseEntered
jLabel43.setVisible(true);
    }//GEN-LAST:event_jLabel40MouseEntered

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
Report.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jLabel40MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseExited
jLabel43.setVisible(false); 
    }//GEN-LAST:event_jLabel40MouseExited

    private void jLabel39MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseEntered
jLabel42.setVisible(true);
    }//GEN-LAST:event_jLabel39MouseEntered

    private void jLabel39MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseExited
jLabel42.setVisible(false);
    }//GEN-LAST:event_jLabel39MouseExited

    private void TransferWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TransferWindowActivated
jLabel42.setVisible(false);
jLabel43.setVisible(false);
    }//GEN-LAST:event_TransferWindowActivated

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
Report.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AboutUsF;
    private javax.swing.JFrame AccDet;
    private javax.swing.JFrame ContactUsF;
    private javax.swing.JLabel I;
    private javax.swing.JLabel I1;
    private javax.swing.JLabel I2;
    private javax.swing.JLabel I3;
    private javax.swing.JLabel I4;
    private javax.swing.JFrame LoggedIn;
    private javax.swing.JFrame LoginMain;
    private javax.swing.JPasswordField PF1;
    private javax.swing.JPasswordField PF2;
    private javax.swing.JPasswordField PF3;
    private javax.swing.JFrame Report;
    private javax.swing.JFrame SignUp;
    private javax.swing.JFrame SignUpConf;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JFrame Transfer;
    private javax.swing.JFrame TransferHist;
    private javax.swing.JFrame Update;
    private javax.swing.JTextArea area;
    private javax.swing.JTextArea area2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scroll2;
    // End of variables declaration//GEN-END:variables
}
